class AmazonPrime{
static String kannadaMovie [] = {"Kgf","Kantara","Om","Super","Naanu","MukundaMurari","Kalpana","Bhudhivanta","Holyhood","H2O","SuperStar","Upendra","A","Shh","KatariVeeraSurasundarangi","Kirataka","Lucky","Rajahuli","Rocky","Modalasala","Gulto","DaredevilMustafa","GuruShishyaru","MrAndMrsRamachari","Milana"}; 
static String hindiMovie[] = {"3Idiots","Ddlj","KuchKuchHotaHai","Bazigar","HumApkeHainKoun","pk","Bhediya","Veer-Zaara","Mausam","SanamTeriKasam","Fanaa","Sultan","MainHoonNa","KabhiKhushiKabhieGham","Dilwale","Kalank","Aashiqui","Saathiya","JabWeMet","DearZindagi","Andhadhun","Blue","EkThaTiger","EkVillain","KoiMilGaya"};
static String teluguMovie[] = {"V","AAa","Bommarillu","Bheeshma","RadheShyam","Baahubali","VinayaVidheyaRama","NannakuPrematho","LoveStory","Maharshi","RRR","EeNagaranikiEmaindi","ArjunReddy","Mirchi","SarkaruVaariPaata","Saaho","AnniManchiSakunamule","GeethaGovinbdam","Businessman","Custody","Rangasthalam","Pushpa","Paagal","DearComrade","Rx100"};
static String tamilMovie[] = {"Remo","Doctor","Veeram","HeySinamika","2.0","Saithan","Anniyan","Ayan","Vaathi","Kaithi","Don","Kutty","Varisu","Ko","OhMyKadavule","Aranmanai","Vaamanan","NGK","96","LoveToday","Vikram","Master","Bachelor","Mahaan","SooraraiPottru"};
static String malayalamMovie[] = {"Hridayam","BangaloreDays","Premam","Trance","Romancham","MadhuraManoharaMoham","Amala","Flush","O.Baby","PachuvumAthbuthaVilakkum","Adi","Kaipola","OmShanthiOshana","Uru","OhMyDarling","Pallimani","Boomerang","Christy","DearVaapi","Rekha","Thankam","Alone","Poovan","Ayisha","Iru"};
public static void main(String amazon[]){

System.out.println("List Of kannada movies are:");
System.out.println(kannadaMovie[0] + " " + kannadaMovie[1] + " " +kannadaMovie[2] + " " +kannadaMovie[3] + " " +kannadaMovie[4] + " " +kannadaMovie[5] + " " +kannadaMovie[6] + " " +kannadaMovie[7] + " " +kannadaMovie[8] + " " +kannadaMovie[9] + " " +kannadaMovie[10] + " " +kannadaMovie[11] + " " +kannadaMovie[12] + " " +kannadaMovie[13] + " " +kannadaMovie[14] + " " +kannadaMovie[15] + " " +kannadaMovie[16] + " " +kannadaMovie[17] + " " +kannadaMovie[18] + " " +kannadaMovie[19] + " " +kannadaMovie[20] + " " +kannadaMovie[21] + " " +kannadaMovie[22] + " " +kannadaMovie[23] + " " +kannadaMovie[24]);

System.out.println("List Of hindi movies are:");
System.out.println(hindiMovie[0] + " " + hindiMovie[1] + " " +hindiMovie[2] + " " +hindiMovie[3] + " " +hindiMovie[4] + " " +hindiMovie[5] + " " +hindiMovie[6] + " " +hindiMovie[7] + " " +hindiMovie[8] + " " +hindiMovie[9] + " " +hindiMovie[10] + " " +hindiMovie[11] + " " +hindiMovie[12] + " " +hindiMovie[13] + " " +hindiMovie[14] + " " +hindiMovie[15] + " " +hindiMovie[16] + " " +hindiMovie[17] + " " +hindiMovie[18] + " " +hindiMovie[19] + " " +hindiMovie[20] + " " +hindiMovie[21] + " " +hindiMovie[22] + " " +hindiMovie[23] + " " +hindiMovie[24]);

System.out.println("List Of telugu movies are:");
System.out.println(teluguMovie[0] + " " + teluguMovie[1] + " " + teluguMovie[2] + " " + teluguMovie[3] + " " + teluguMovie[4] + " " + teluguMovie[5] + " " + teluguMovie[6] + " " + teluguMovie[7] + " " + teluguMovie[8] + " " + teluguMovie[9] + " " + teluguMovie[10] + " " + teluguMovie[11] + " " + teluguMovie[12] + " " + teluguMovie[13] + " " + teluguMovie[14] + " " + teluguMovie[15] + " " + teluguMovie[16] + " " + teluguMovie[17] + " " + teluguMovie[18] + " " + teluguMovie[19] + " " + teluguMovie[20] + " " + teluguMovie[21] + " " + teluguMovie[22] + " " + teluguMovie[23] + " " + teluguMovie[24] );

System.out.println("List Of tamil movies are:");
System.out.println(tamilMovie[0] + " " + tamilMovie[1] + " " + tamilMovie[2] + " " + tamilMovie[3] + " " +tamilMovie[4] + " " +tamilMovie[5] + " " +tamilMovie[6] + " " +tamilMovie[7] + " " +tamilMovie[8] + " " +tamilMovie[9] + " " +tamilMovie[10] + " " +tamilMovie[11] + " " +tamilMovie[12] + " " +tamilMovie[13] + " " +tamilMovie[14] + " " +tamilMovie[15] + " " +tamilMovie[16] + " " +tamilMovie[17] + " " +tamilMovie[18] + " " +tamilMovie[19] + " " +tamilMovie[20] + " " +tamilMovie[21] + " " +tamilMovie[22] + " " +tamilMovie[23] + " " +tamilMovie[24] );

System.out.println("List Of malayalam movies are:");
System.out.println(malayalamMovie[0] + " " +malayalamMovie[1] + " " +malayalamMovie[2] + " " +malayalamMovie[3] + " " +malayalamMovie[4] + " " +malayalamMovie[5] + " " +malayalamMovie[6] + " " +malayalamMovie[7] + " " +malayalamMovie[8] + " " +malayalamMovie[9] + " " +malayalamMovie[10] + " " +malayalamMovie[11] + " " +malayalamMovie[12] + " " +malayalamMovie[13] + " " +malayalamMovie[14] + " " +malayalamMovie[15] + " " +malayalamMovie[16] + " " +malayalamMovie[17] + " " +malayalamMovie[18] + " " +malayalamMovie[19] + " " +malayalamMovie[20] + " " +malayalamMovie[21] + " " +malayalamMovie[22] + " " +malayalamMovie[23] + " " +malayalamMovie[24]);

}
}